-- Baseline de schema — 2026-07-27
--
-- Este projeto nunca teve pasta supabase/migrations/: todo o schema (tabelas,
-- funções, policies de RLS, triggers, índices) foi criado direto em produção,
-- sem versionamento no git. Esta migration reconstrói o estado atual do banco
-- por introspecção (information_schema, pg_policies, pg_get_functiondef,
-- pg_indexes) — não é um `pg_dump`/`supabase db pull` real, então pode não
-- ser byte-a-byte idêntica ao histórico original de comandos, mas reflete
-- fielmente a estrutura como ela existe hoje.
--
-- É seguro rodar mais de uma vez (tudo usa IF NOT EXISTS / OR REPLACE /
-- DROP...IF EXISTS antes de recriar), porque quando isso foi aplicado pela
-- primeira vez as tabelas já existiam — o objetivo não era recriar nada, era
-- só passar a existir localmente e ficar registrado no histórico de
-- migrations do Supabase, pra que a partir de agora toda mudança de schema
-- (nova coluna, nova policy, etc.) vire uma migration nova em vez de SQL solto
-- direto em produção.
--
-- Atenção: o histórico remoto (supabase_migrations.schema_migrations) já
-- tinha 3 migrations aplicadas ANTES desta baseline, que nunca tinham
-- arquivo local correspondente:
--   20260722232214 50_restringe_update_lojas_a_owner
--   20260723005539 status_assinatura_efetiva_cobre_rede_do_dono
--   20260723172552 51_corrige_recursao_insert_nova_loja
-- O efeito das três já está refletido nesta baseline (policy "update_propria_loja"
-- e "insert_nova_loja" de lojas, e a função status_assinatura_efetiva, já
-- estão na versão corrigida). Não foram recriadas como arquivos separados
-- porque não temos o estado "antes" delas salvo em lugar nenhum — só o
-- resultado final. Se um dia alguém rodar `supabase db pull` com acesso
-- autenticado ao projeto, pode aparecer um aviso de divergência por causa
-- dessas 3 — é esperado, não é bug desta baseline.

-- ============================================================
-- TABELAS
-- ============================================================

create table if not exists public.lojas (
  id bigint generated always as identity primary key,
  nome text not null,
  endereco text,
  cor_destaque text default '#3ecf6e'::text,
  created_at timestamptz default now(),
  cidade text,
  cnpj text,
  tel text,
  logo text,
  ativa boolean not null default true,
  cobranca_para text not null default 'loja'::text
    check (cobranca_para = any (array['loja'::text,'dono'::text])),
  ordem integer not null default 0
);

create table if not exists public.perfis (
  id uuid primary key references auth.users(id),
  nome text not null,
  email text not null,
  role text not null default 'owner'::text,
  loja_id bigint references public.lojas(id),
  is_admin boolean default false,
  created_at timestamptz default now(),
  cpf text,
  ordem integer not null default 0
);

create table if not exists public.loja_membros (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id),
  loja_id bigint not null references public.lojas(id),
  role text not null default 'owner'::text,
  created_at timestamptz not null default now(),
  unique (user_id, loja_id)
);

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  loja_id bigint not null references public.lojas(id),
  chave text not null,
  nome text not null,
  emoji text not null default '📦'::text,
  ordem integer not null default 99,
  ativa boolean not null default true,
  unique (loja_id, chave)
);

create table if not exists public.produtos (
  id bigint generated always as identity primary key,
  loja_id bigint not null references public.lojas(id),
  categoria text not null,
  nome text not null,
  tipo text not null default 'caixa'::text
    check (tipo = any (array['caixa'::text,'unidade'::text])),
  unid_por_caixa numeric,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  ordem integer not null default 0,
  unique (loja_id, categoria, nome)
);

create table if not exists public.fornecedores (
  id bigint generated always as identity primary key,
  loja_id bigint references public.lojas(id),
  nome text not null,
  categoria text not null,
  padrao boolean default false,
  created_at timestamptz default now(),
  ordem integer not null default 0
);

create table if not exists public.despesas_tipos (
  id bigint generated always as identity primary key,
  loja_id bigint not null references public.lojas(id),
  nome text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  ordem integer not null default 0,
  unique (loja_id, nome)
);

create table if not exists public.itens_pedido (
  id bigint generated always as identity primary key,
  loja_id bigint references public.lojas(id),
  data date not null,
  produto text not null,
  categoria text not null,
  qtd numeric not null,
  tipo text default 'caixa'::text,
  unid_por_caixa integer,
  status text default 'pendente'::text,
  created_at timestamptz default now()
);

create table if not exists public.compras (
  id bigint generated always as identity primary key,
  loja_id bigint references public.lojas(id),
  item_pedido_id bigint references public.itens_pedido(id),
  data date not null,
  produto text not null,
  categoria text not null,
  qtd numeric not null,
  valor_unit numeric not null,
  fornecedor text not null,
  pagamento text not null,
  created_at timestamptz default now()
);

create table if not exists public.despesas (
  id bigint generated always as identity primary key,
  loja_id bigint references public.lojas(id),
  data date not null,
  descricao text not null,
  valor numeric not null,
  forma text not null,
  created_at timestamptz default now()
);

create table if not exists public.margens_custom (
  id bigint generated always as identity primary key,
  loja_id bigint references public.lojas(id),
  produto text not null,
  tipo text not null,
  valor numeric not null,
  updated_at timestamptz default now(),
  unique (loja_id, produto)
);

create table if not exists public.assinaturas (
  id bigint generated always as identity primary key,
  loja_id bigint unique references public.lojas(id),
  status text not null default 'trial'::text,
  plano text not null default 'mensal'::text,
  valor_mensal numeric not null default 250,
  trial_inicio date not null default current_date,
  trial_fim date not null default (current_date + interval '3 days'),
  proxima_cobranca date,
  asaas_customer_id text,
  asaas_sub_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  vinculada_loja_id bigint references public.lojas(id),
  ultima_tentativa_cobranca timestamptz
);

create table if not exists public."cobranças" (
  id bigint generated always as identity primary key,
  loja_id bigint references public.lojas(id),
  assinatura_id bigint references public.assinaturas(id),
  asaas_charge_id text,
  valor numeric not null,
  status text not null default 'pendente'::text,
  vencimento date,
  pago_em timestamptz,
  link_pagamento text,
  created_at timestamptz default now()
);

create table if not exists public.convites_usuario (
  id bigint generated always as identity primary key,
  email text not null,
  loja_id bigint not null references public.lojas(id),
  role text not null default 'manager'::text
    check (role = any (array['manager'::text,'pedidos'::text,'comprador'::text])),
  criado_por uuid references auth.users(id),
  usado boolean not null default false,
  created_at timestamptz not null default now(),
  telefone text,
  unique (email, loja_id)
);

create table if not exists public.config_sistema (
  id bigint generated always as identity primary key,
  chave text not null unique,
  valor text,
  updated_at timestamptz default now()
);

-- ============================================================
-- ÍNDICES (além dos criados implicitamente por PK/UNIQUE acima)
-- ============================================================

create index if not exists idx_compras_loja_data on public.compras using btree (loja_id, data);
create index if not exists idx_despesas_loja_data on public.despesas using btree (loja_id, data);
create index if not exists idx_fornecedores_loja_cat on public.fornecedores using btree (loja_id, categoria);
create index if not exists idx_itens_pedido_loja_data on public.itens_pedido using btree (loja_id, data);
create index if not exists idx_produtos_loja on public.produtos using btree (loja_id);

-- ============================================================
-- ROW LEVEL SECURITY — habilita em todas as tabelas
-- ============================================================

alter table public.lojas enable row level security;
alter table public.perfis enable row level security;
alter table public.loja_membros enable row level security;
alter table public.categorias enable row level security;
alter table public.produtos enable row level security;
alter table public.fornecedores enable row level security;
alter table public.despesas_tipos enable row level security;
alter table public.itens_pedido enable row level security;
alter table public.compras enable row level security;
alter table public.despesas enable row level security;
alter table public.margens_custom enable row level security;
alter table public.assinaturas enable row level security;
alter table public."cobranças" enable row level security;
alter table public.convites_usuario enable row level security;
alter table public.config_sistema enable row level security;

-- ============================================================
-- FUNÇÕES HELPER (usadas dentro das policies — precisam existir primeiro)
-- ============================================================

create or replace function public.sou_admin()
 returns boolean
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select coalesce(is_admin, false) from perfis where id = auth.uid();
$function$;

create or replace function public.minha_loja_id()
 returns bigint
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select loja_id from perfis where id = auth.uid();
$function$;

create or replace function public.loja_tem_perfil(p_loja_id bigint)
 returns boolean
 language sql
 stable security definer
 set search_path to 'public'
as $function$
  select exists (select 1 from perfis where loja_id = p_loja_id);
$function$;

-- ============================================================
-- POLICIES DE RLS
-- ============================================================

-- lojas
drop policy if exists "insert_nova_loja" on public.lojas;
create policy "insert_nova_loja" on public.lojas
for insert to authenticated
with check (
  sou_admin()
  or (
    (select count(*) from loja_membros lm
     where lm.user_id = auth.uid()
       and lm.role = 'owner'
       and lm.created_at > (now() - interval '24:00:00')) < 5
  )
);

drop policy if exists "select_propria_loja_ou_recem_criada" on public.lojas;
create policy "select_propria_loja_ou_recem_criada" on public.lojas
for select to authenticated
using (
  (id = minha_loja_id())
  or sou_admin()
  or (not exists (select 1 from perfis where perfis.loja_id = lojas.id))
);

drop policy if exists "update_propria_loja" on public.lojas;
create policy "update_propria_loja" on public.lojas
for update to authenticated
using (
  sou_admin()
  or exists (
    select 1 from loja_membros
    where loja_membros.loja_id = lojas.id
      and loja_membros.user_id = auth.uid()
      and loja_membros.role = 'owner'
  )
);

-- perfis
drop policy if exists "Usuário cria o próprio perfil no cadastro" on public.perfis;
create policy "Usuário cria o próprio perfil no cadastro" on public.perfis
for insert
with check (
  (id = auth.uid())
  and (
    sou_admin()
    or (role = 'owner'::text and not loja_tem_perfil(loja_id))
    or exists (
      select 1 from convites_usuario c
      where c.loja_id = perfis.loja_id
        and c.role = perfis.role
        and lower(trim(c.email)) = lower(trim(auth.jwt() ->> 'email'::text))
        and c.usado = true
    )
  )
);

drop policy if exists "Usuário vê o próprio perfil" on public.perfis;
create policy "Usuário vê o próprio perfil" on public.perfis
for select
using (
  (id = auth.uid())
  or sou_admin()
  or exists (
    select 1 from loja_membros
    where loja_membros.user_id = auth.uid()
      and loja_membros.role = 'owner'::text
      and loja_membros.loja_id = perfis.loja_id
  )
);

drop policy if exists "Usuário edita o próprio perfil" on public.perfis;
create policy "Usuário edita o próprio perfil" on public.perfis
for update
using (id = auth.uid())
with check (
  (id = auth.uid())
  and (
    loja_id is null
    or sou_admin()
    or exists (
      select 1 from loja_membros
      where loja_membros.user_id = auth.uid()
        and loja_membros.loja_id = perfis.loja_id
    )
  )
);

drop policy if exists "Dono reatribui gerente entre suas lojas" on public.perfis;
create policy "Dono reatribui gerente entre suas lojas" on public.perfis
for update
using (
  (role = any (array['manager'::text,'pedidos'::text]))
  and exists (
    select 1 from loja_membros
    where loja_membros.user_id = auth.uid()
      and loja_membros.role = 'owner'::text
      and loja_membros.loja_id = perfis.loja_id
  )
)
with check (
  (role = any (array['manager'::text,'pedidos'::text]))
  and exists (
    select 1 from loja_membros
    where loja_membros.user_id = auth.uid()
      and loja_membros.role = 'owner'::text
      and loja_membros.loja_id = perfis.loja_id
  )
);

drop policy if exists "Dono remove gerentes da sua loja" on public.perfis;
create policy "Dono remove gerentes da sua loja" on public.perfis
for delete
using (
  (role = any (array['manager'::text,'pedidos'::text]))
  and exists (
    select 1 from loja_membros
    where loja_membros.user_id = auth.uid()
      and loja_membros.role = 'owner'::text
      and loja_membros.loja_id = perfis.loja_id
  )
);

-- loja_membros
drop policy if exists "Usuário se registra como dono da loja que criou" on public.loja_membros;
create policy "Usuário se registra como dono da loja que criou" on public.loja_membros
for insert
with check (user_id = auth.uid());

drop policy if exists "Usuário vê suas próprias lojas" on public.loja_membros;
create policy "Usuário vê suas próprias lojas" on public.loja_membros
for select
using ((user_id = auth.uid()) or sou_admin());

drop policy if exists "Usuário sai de uma loja (remove seu próprio vínculo)" on public.loja_membros;
create policy "Usuário sai de uma loja (remove seu próprio vínculo)" on public.loja_membros
for delete
using (user_id = auth.uid());

drop policy if exists "Dono remove vinculo de comprador da sua loja" on public.loja_membros;
create policy "Dono remove vinculo de comprador da sua loja" on public.loja_membros
for delete
using (
  (role = 'comprador'::text)
  and exists (
    select 1 from loja_membros lm2
    where lm2.user_id = auth.uid()
      and lm2.role = 'owner'::text
      and lm2.loja_id = loja_membros.loja_id
  )
);

drop policy if exists "Admin gerencia membros" on public.loja_membros;
create policy "Admin gerencia membros" on public.loja_membros
for all
using (sou_admin());

-- categorias
drop policy if exists "select_categorias" on public.categorias;
create policy "select_categorias" on public.categorias
for select
using (
  (loja_id = minha_loja_id())
  or exists (select 1 from loja_membros where loja_membros.user_id = auth.uid() and loja_membros.loja_id = categorias.loja_id)
  or sou_admin()
);

drop policy if exists "insert_categorias" on public.categorias;
create policy "insert_categorias" on public.categorias
for insert
with check ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "update_categorias" on public.categorias;
create policy "update_categorias" on public.categorias
for update
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "delete_categorias" on public.categorias;
create policy "delete_categorias" on public.categorias
for delete
using ((loja_id = minha_loja_id()) or sou_admin());

-- produtos
drop policy if exists "Ver produtos da propria loja" on public.produtos;
create policy "Ver produtos da propria loja" on public.produtos
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Inserir produtos na propria loja" on public.produtos;
create policy "Inserir produtos na propria loja" on public.produtos
for insert
with check ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Editar produtos da propria loja" on public.produtos;
create policy "Editar produtos da propria loja" on public.produtos
for update
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Excluir produtos da propria loja" on public.produtos;
create policy "Excluir produtos da propria loja" on public.produtos
for delete
using ((loja_id = minha_loja_id()) or sou_admin());

-- fornecedores
drop policy if exists "Vê fornecedores da própria loja" on public.fornecedores;
create policy "Vê fornecedores da própria loja" on public.fornecedores
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Cria fornecedores na própria loja" on public.fornecedores;
create policy "Cria fornecedores na própria loja" on public.fornecedores
for insert
with check (loja_id = minha_loja_id());

drop policy if exists "Edita fornecedores da própria loja" on public.fornecedores;
create policy "Edita fornecedores da própria loja" on public.fornecedores
for update
using (loja_id = minha_loja_id());

drop policy if exists "Remove fornecedores da própria loja" on public.fornecedores;
create policy "Remove fornecedores da própria loja" on public.fornecedores
for delete
using (loja_id = minha_loja_id());

-- despesas_tipos
drop policy if exists "Ver tipos de despesa da propria loja" on public.despesas_tipos;
create policy "Ver tipos de despesa da propria loja" on public.despesas_tipos
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Inserir tipos de despesa na propria loja" on public.despesas_tipos;
create policy "Inserir tipos de despesa na propria loja" on public.despesas_tipos
for insert
with check ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Editar tipos de despesa da propria loja" on public.despesas_tipos;
create policy "Editar tipos de despesa da propria loja" on public.despesas_tipos
for update
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Excluir tipos de despesa da propria loja" on public.despesas_tipos;
create policy "Excluir tipos de despesa da propria loja" on public.despesas_tipos
for delete
using ((loja_id = minha_loja_id()) or sou_admin());

-- itens_pedido
drop policy if exists "Vê pedidos da própria loja" on public.itens_pedido;
create policy "Vê pedidos da própria loja" on public.itens_pedido
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Cria pedidos na própria loja" on public.itens_pedido;
create policy "Cria pedidos na própria loja" on public.itens_pedido
for insert
with check (loja_id = minha_loja_id());

drop policy if exists "Edita pedidos da própria loja" on public.itens_pedido;
create policy "Edita pedidos da própria loja" on public.itens_pedido
for update
using (loja_id = minha_loja_id());

drop policy if exists "Remove pedidos da própria loja" on public.itens_pedido;
create policy "Remove pedidos da própria loja" on public.itens_pedido
for delete
using (loja_id = minha_loja_id());

drop policy if exists "Dono ve pedidos de todas as suas lojas" on public.itens_pedido;
create policy "Dono ve pedidos de todas as suas lojas" on public.itens_pedido
for select
using (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'owner'::text and loja_membros.loja_id = itens_pedido.loja_id
));

drop policy if exists "Dono atualiza pedidos de todas as suas lojas" on public.itens_pedido;
create policy "Dono atualiza pedidos de todas as suas lojas" on public.itens_pedido
for update
using (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'owner'::text and loja_membros.loja_id = itens_pedido.loja_id
));

drop policy if exists "Comprador ve pedidos das lojas vinculadas" on public.itens_pedido;
create policy "Comprador ve pedidos das lojas vinculadas" on public.itens_pedido
for select
using (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'comprador'::text and loja_membros.loja_id = itens_pedido.loja_id
));

drop policy if exists "Comprador atualiza pedidos das lojas vinculadas" on public.itens_pedido;
create policy "Comprador atualiza pedidos das lojas vinculadas" on public.itens_pedido
for update
using (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'comprador'::text and loja_membros.loja_id = itens_pedido.loja_id
));

-- compras
drop policy if exists "Vê compras da própria loja" on public.compras;
create policy "Vê compras da própria loja" on public.compras
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Cria compras na própria loja" on public.compras;
create policy "Cria compras na própria loja" on public.compras
for insert
with check (loja_id = minha_loja_id());

drop policy if exists "Edita compras da própria loja" on public.compras;
create policy "Edita compras da própria loja" on public.compras
for update
using (loja_id = minha_loja_id());

drop policy if exists "Remove compras da própria loja" on public.compras;
create policy "Remove compras da própria loja" on public.compras
for delete
using (loja_id = minha_loja_id());

drop policy if exists "Dono ve compras de todas as suas lojas" on public.compras;
create policy "Dono ve compras de todas as suas lojas" on public.compras
for select
using (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'owner'::text and loja_membros.loja_id = compras.loja_id
));

drop policy if exists "Dono insere compras de todas as suas lojas" on public.compras;
create policy "Dono insere compras de todas as suas lojas" on public.compras
for insert
with check (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'owner'::text and loja_membros.loja_id = compras.loja_id
));

drop policy if exists "Comprador ve compras das lojas vinculadas" on public.compras;
create policy "Comprador ve compras das lojas vinculadas" on public.compras
for select
using (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'comprador'::text and loja_membros.loja_id = compras.loja_id
));

drop policy if exists "Comprador insere compras das lojas vinculadas" on public.compras;
create policy "Comprador insere compras das lojas vinculadas" on public.compras
for insert
with check (exists (
  select 1 from loja_membros
  where loja_membros.user_id = auth.uid() and loja_membros.role = 'comprador'::text and loja_membros.loja_id = compras.loja_id
));

-- despesas
drop policy if exists "Vê despesas da própria loja" on public.despesas;
create policy "Vê despesas da própria loja" on public.despesas
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Cria despesas na própria loja" on public.despesas;
create policy "Cria despesas na própria loja" on public.despesas
for insert
with check (loja_id = minha_loja_id());

drop policy if exists "Edita despesas da própria loja" on public.despesas;
create policy "Edita despesas da própria loja" on public.despesas
for update
using (loja_id = minha_loja_id());

drop policy if exists "Remove despesas da própria loja" on public.despesas;
create policy "Remove despesas da própria loja" on public.despesas
for delete
using (loja_id = minha_loja_id());

-- margens_custom
drop policy if exists "Vê margens da própria loja" on public.margens_custom;
create policy "Vê margens da própria loja" on public.margens_custom
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Cria margens na própria loja" on public.margens_custom;
create policy "Cria margens na própria loja" on public.margens_custom
for insert
with check (loja_id = minha_loja_id());

drop policy if exists "Edita margens da própria loja" on public.margens_custom;
create policy "Edita margens da própria loja" on public.margens_custom
for update
using (loja_id = minha_loja_id());

drop policy if exists "Remove margens da própria loja" on public.margens_custom;
create policy "Remove margens da própria loja" on public.margens_custom
for delete
using (loja_id = minha_loja_id());

-- assinaturas
drop policy if exists "Ver propria assinatura" on public.assinaturas;
create policy "Ver propria assinatura" on public.assinaturas
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Inserir propria assinatura" on public.assinaturas;
create policy "Inserir propria assinatura" on public.assinaturas
for insert
with check ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Admin gerencia assinaturas" on public.assinaturas;
create policy "Admin gerencia assinaturas" on public.assinaturas
for all
using (sou_admin())
with check (sou_admin());

-- cobranças
drop policy if exists "Ver proprias cobranças" on public."cobranças";
create policy "Ver proprias cobranças" on public."cobranças"
for select
using ((loja_id = minha_loja_id()) or sou_admin());

drop policy if exists "Admin gerencia cobranças" on public."cobranças";
create policy "Admin gerencia cobranças" on public."cobranças"
for all
using (sou_admin())
with check (sou_admin());

-- convites_usuario
drop policy if exists "Ver convites" on public.convites_usuario;
create policy "Ver convites" on public.convites_usuario
for select
using (
  (criado_por = auth.uid())
  or sou_admin()
  or (usado = false)
  or (lower(trim(email)) = lower(trim(auth.jwt() ->> 'email'::text)))
);

drop policy if exists "Dono cria convite da propria loja" on public.convites_usuario;
create policy "Dono cria convite da propria loja" on public.convites_usuario
for insert
with check (
  (criado_por = auth.uid())
  and exists (
    select 1 from loja_membros
    where loja_membros.user_id = auth.uid() and loja_membros.loja_id = convites_usuario.loja_id and loja_membros.role = 'owner'::text
  )
);

drop policy if exists "Marcar convite como usado no cadastro" on public.convites_usuario;
create policy "Marcar convite como usado no cadastro" on public.convites_usuario
for update
using (
  (usado = false) and (lower(trim(email)) = lower(trim(auth.jwt() ->> 'email'::text)))
)
with check (
  (usado = true) and (lower(trim(email)) = lower(trim(auth.jwt() ->> 'email'::text)))
);

drop policy if exists "Dono remove convite da propria loja" on public.convites_usuario;
create policy "Dono remove convite da propria loja" on public.convites_usuario
for delete
using ((criado_por = auth.uid()) or sou_admin());

-- config_sistema
drop policy if exists "Admin gerencia config" on public.config_sistema;
create policy "Admin gerencia config" on public.config_sistema
for all
using (sou_admin())
with check (sou_admin());

-- ============================================================
-- DEMAIS FUNÇÕES (RPCs chamadas do app + funções de trigger)
-- ============================================================

create or replace function public.assinaturas_das_minhas_lojas()
 returns table(loja_id bigint, nome text, logo text, status text, proxima_cobranca date, valor_mensal numeric, vinculada_loja_id bigint)
 language sql
 security definer
 set search_path to 'public'
as $function$
  select l.id, l.nome, l.logo,
    coalesce(a.status, 'sem_assinatura') as status,
    a.proxima_cobranca,
    coalesce(a.valor_mensal, 250) as valor_mensal,
    a.vinculada_loja_id
  from lojas l
  join loja_membros lm on lm.loja_id = l.id and lm.user_id = auth.uid() and lm.role = 'owner'
  left join assinaturas a on a.loja_id = l.id
  where coalesce(l.ativa, true) = true
  order by l.nome;
$function$;

create or replace function public.convidar_ou_vincular_comprador(p_email text, p_loja_id bigint)
 returns text
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_user_id uuid;
  v_role text;
begin
  if not exists (
    select 1 from loja_membros
    where user_id = auth.uid() and role = 'owner' and loja_id = p_loja_id
  ) and not sou_admin() then
    raise exception 'Você não tem permissão para convidar comprador pra essa loja';
  end if;

  select id into v_user_id from auth.users where lower(email) = lower(p_email) limit 1;

  if v_user_id is not null then
    select role into v_role from perfis where id = v_user_id;
    if v_role is distinct from 'comprador' then
      raise exception 'Esse e-mail já tem uma conta com outro tipo de acesso (%). Use outro e-mail para o comprador.', coalesce(v_role, 'desconhecido');
    end if;
    insert into loja_membros (user_id, loja_id, role)
    values (v_user_id, p_loja_id, 'comprador')
    on conflict (user_id, loja_id) do nothing;
    return 'vinculado';
  else
    insert into convites_usuario (email, loja_id, role, criado_por)
    values (lower(p_email), p_loja_id, 'comprador', auth.uid())
    on conflict (email, loja_id) do nothing;
    return 'convite_criado';
  end if;
end;
$function$;

create or replace function public.criar_categoria_import(p_loja_id bigint, p_chave text, p_nome text, p_emoji text, p_ordem integer)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  if not (
    sou_admin()
    or exists(select 1 from loja_membros where user_id = auth.uid() and loja_membros.loja_id = p_loja_id)
    or exists(select 1 from perfis where id = auth.uid() and perfis.loja_id = p_loja_id)
  ) then
    raise exception 'Sem permissão pra criar categoria nessa loja';
  end if;

  insert into categorias (loja_id, chave, nome, emoji, ordem, ativa)
  values (p_loja_id, p_chave, p_nome, p_emoji, p_ordem, true)
  on conflict (loja_id, chave) do update set nome = excluded.nome, emoji = excluded.emoji;
end;
$function$;

create or replace function public.criar_categorias_padrao()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  insert into categorias (loja_id, chave, nome, emoji, ordem) values
    (new.id, 'fruta', 'Frutas', '🍊', 1),
    (new.id, 'legume', 'Legumes', '🥕', 2),
    (new.id, 'verdura', 'Verduras', '🥬', 3);
  return new;
end;
$function$;

create or replace function public.criar_membro_dono_loja()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  if auth.uid() is not null then
    insert into loja_membros (user_id, loja_id, role)
    values (auth.uid(), new.id, 'owner')
    on conflict (user_id, loja_id) do nothing;
  end if;
  return new;
end;
$function$;

create or replace function public.criar_trial_automatico()
 returns trigger
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
begin
  insert into assinaturas (loja_id, status, trial_inicio, trial_fim)
  values (new.id, 'trial', current_date, current_date + interval '3 days')
  on conflict (loja_id) do nothing;
  return new;
end;
$function$;

create or replace function public.excluir_loja_definitivamente(p_loja_id bigint)
 returns void
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  r record;
  fallback_loja_id bigint;
begin
  if not sou_admin() then
    raise exception 'Apenas o admin master pode excluir uma loja definitivamente';
  end if;

  -- Reatribui qualquer perfil que esteja com essa loja como ativa
  -- pra outra loja que a mesma pessoa também é dona, se existir
  for r in select id from perfis where loja_id = p_loja_id loop
    select lm.loja_id into fallback_loja_id
    from loja_membros lm
    where lm.user_id = r.id and lm.loja_id != p_loja_id
    order by lm.loja_id
    limit 1;

    if fallback_loja_id is not null then
      update perfis set loja_id = fallback_loja_id where id = r.id;
    else
      raise exception 'Não é possível excluir: o perfil % ficaria sem nenhuma loja. Vincule esse usuário a outra loja antes de excluir esta.', r.id;
    end if;
  end loop;

  delete from itens_pedido where loja_id = p_loja_id;
  delete from compras where loja_id = p_loja_id;
  delete from despesas where loja_id = p_loja_id;
  delete from margens_custom where loja_id = p_loja_id;
  delete from fornecedores where loja_id = p_loja_id;
  delete from produtos where loja_id = p_loja_id;
  delete from despesas_tipos where loja_id = p_loja_id;
  delete from "cobranças" where loja_id = p_loja_id;
  delete from assinaturas where loja_id = p_loja_id;
  delete from convites_usuario where loja_id = p_loja_id;
  delete from loja_membros where loja_id = p_loja_id;
  delete from lojas where id = p_loja_id;
end;
$function$;

create or replace function public.status_assinatura_efetiva(p_loja_id bigint)
 returns table(status text, trial_fim date, proxima_cobranca date, valor_mensal numeric, plano text)
 language plpgsql
 security definer
 set search_path to 'public'
as $function$
declare
  v_sub record;
  v_melhor record;
begin
  -- só deixa consultar se quem está chamando tem alguma relação real com essa loja
  if not (
    exists(select 1 from loja_membros where user_id = auth.uid() and loja_membros.loja_id = p_loja_id)
    or exists(select 1 from perfis where id = auth.uid() and perfis.loja_id = p_loja_id)
    or sou_admin()
  ) then
    raise exception 'Sem permissão pra ver a assinatura dessa loja';
  end if;

  select * into v_sub from assinaturas where loja_id = p_loja_id;

  -- compatibilidade com o encadeamento manual já existente (isenta + vinculada_loja_id)
  if v_sub.status = 'isenta' and v_sub.vinculada_loja_id is not null then
    select * into v_sub from assinaturas where loja_id = v_sub.vinculada_loja_id;
  end if;

  -- se a própria loja (ou a loja vinculada manualmente) já está ativa/isenta, não
  -- precisa olhar a rede — devolve direto
  if v_sub.status in ('ativa','isenta') then
    return query select v_sub.status, v_sub.trial_fim, v_sub.proxima_cobranca, v_sub.valor_mensal, v_sub.plano;
    return;
  end if;

  -- rede: se QUALQUER outra loja onde o(s) mesmo(s) dono(s) desta loja também é
  -- owner estiver ativa/isenta, essa loja também fica liberada — sem precisar
  -- configurar vinculada_loja_id manualmente toda vez que uma loja nova entra
  -- na rede.
  select a.* into v_melhor
  from assinaturas a
  where a.loja_id in (
    select lm2.loja_id
    from loja_membros lm1
    join loja_membros lm2 on lm2.user_id = lm1.user_id and lm2.role = 'owner'
    where lm1.loja_id = p_loja_id and lm1.role = 'owner'
  )
  and a.status in ('ativa','isenta')
  order by (a.status = 'ativa') desc, a.proxima_cobranca desc nulls last
  limit 1;

  if v_melhor.status is not null then
    return query select v_melhor.status, v_melhor.trial_fim, v_melhor.proxima_cobranca, v_melhor.valor_mensal, v_melhor.plano;
    return;
  end if;

  -- ninguém da rede está pago — devolve o status real da própria loja (trial/vencida)
  return query select v_sub.status, v_sub.trial_fim, v_sub.proxima_cobranca, v_sub.valor_mensal, v_sub.plano;
end;
$function$;

-- ============================================================
-- TRIGGERS
-- ============================================================

drop trigger if exists trg_criar_membro_dono_loja on public.lojas;
create trigger trg_criar_membro_dono_loja
  after insert on public.lojas
  for each row execute function public.criar_membro_dono_loja();

drop trigger if exists trigger_criar_categorias_padrao on public.lojas;
create trigger trigger_criar_categorias_padrao
  after insert on public.lojas
  for each row execute function public.criar_categorias_padrao();

drop trigger if exists trigger_trial_automatico on public.lojas;
create trigger trigger_trial_automatico
  after insert on public.lojas
  for each row execute function public.criar_trial_automatico();
